// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: glassharbor/registry/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the x/registry parameters (SPEC §6.1).
type Params struct {
	CreateAppFee            types.Coin                  `protobuf:"bytes,1,opt,name=create_app_fee,json=createAppFee,proto3" json:"create_app_fee"`
	PublishVersionFee       types.Coin                  `protobuf:"bytes,2,opt,name=publish_version_fee,json=publishVersionFee,proto3" json:"publish_version_fee"`
	UploadFeeTreasuryRate   cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=upload_fee_treasury_rate,json=uploadFeeTreasuryRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"upload_fee_treasury_rate"`
	BluecheckTreasuryRate   cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=bluecheck_treasury_rate,json=bluecheckTreasuryRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"bluecheck_treasury_rate"`
	TreasuryAddress         string                      `protobuf:"bytes,5,opt,name=treasury_address,json=treasuryAddress,proto3" json:"treasury_address,omitempty"`
	VotingPeriod            time.Duration               `protobuf:"bytes,6,opt,name=voting_period,json=votingPeriod,proto3,stdduration" json:"voting_period"`
	Categories              []string                    `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	MaxTitleBytes           uint32                      `protobuf:"varint,8,opt,name=max_title_bytes,json=maxTitleBytes,proto3" json:"max_title_bytes,omitempty"`
	MaxDescriptionBytes     uint32                      `protobuf:"varint,9,opt,name=max_description_bytes,json=maxDescriptionBytes,proto3" json:"max_description_bytes,omitempty"`
	MaxTags                 uint32                      `protobuf:"varint,10,opt,name=max_tags,json=maxTags,proto3" json:"max_tags,omitempty"`
	MaxTagBytes             uint32                      `protobuf:"varint,11,opt,name=max_tag_bytes,json=maxTagBytes,proto3" json:"max_tag_bytes,omitempty"`
	MaxIconBytes            uint32                      `protobuf:"varint,12,opt,name=max_icon_bytes,json=maxIconBytes,proto3" json:"max_icon_bytes,omitempty"`
	MaxMagnetBytes          uint32                      `protobuf:"varint,13,opt,name=max_magnet_bytes,json=maxMagnetBytes,proto3" json:"max_magnet_bytes,omitempty"`
	MaxMinJettyVersionBytes uint32                      `protobuf:"varint,14,opt,name=max_min_jetty_version_bytes,json=maxMinJettyVersionBytes,proto3" json:"max_min_jetty_version_bytes,omitempty"`
	MaxWebsiteBytes         uint32                      `protobuf:"varint,15,opt,name=max_website_bytes,json=maxWebsiteBytes,proto3" json:"max_website_bytes,omitempty"`
	MaxSourceUrlBytes       uint32                      `protobuf:"varint,16,opt,name=max_source_url_bytes,json=maxSourceUrlBytes,proto3" json:"max_source_url_bytes,omitempty"`
	MaxVersionBytes         uint32                      `protobuf:"varint,17,opt,name=max_version_bytes,json=maxVersionBytes,proto3" json:"max_version_bytes,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_38670aa0275c922c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCreateAppFee() types.Coin {
	if m != nil {
		return m.CreateAppFee
	}
	return types.Coin{}
}

func (m *Params) GetPublishVersionFee() types.Coin {
	if m != nil {
		return m.PublishVersionFee
	}
	return types.Coin{}
}

func (m *Params) GetTreasuryAddress() string {
	if m != nil {
		return m.TreasuryAddress
	}
	return ""
}

func (m *Params) GetVotingPeriod() time.Duration {
	if m != nil {
		return m.VotingPeriod
	}
	return 0
}

func (m *Params) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Params) GetMaxTitleBytes() uint32 {
	if m != nil {
		return m.MaxTitleBytes
	}
	return 0
}

func (m *Params) GetMaxDescriptionBytes() uint32 {
	if m != nil {
		return m.MaxDescriptionBytes
	}
	return 0
}

func (m *Params) GetMaxTags() uint32 {
	if m != nil {
		return m.MaxTags
	}
	return 0
}

func (m *Params) GetMaxTagBytes() uint32 {
	if m != nil {
		return m.MaxTagBytes
	}
	return 0
}

func (m *Params) GetMaxIconBytes() uint32 {
	if m != nil {
		return m.MaxIconBytes
	}
	return 0
}

func (m *Params) GetMaxMagnetBytes() uint32 {
	if m != nil {
		return m.MaxMagnetBytes
	}
	return 0
}

func (m *Params) GetMaxMinJettyVersionBytes() uint32 {
	if m != nil {
		return m.MaxMinJettyVersionBytes
	}
	return 0
}

func (m *Params) GetMaxWebsiteBytes() uint32 {
	if m != nil {
		return m.MaxWebsiteBytes
	}
	return 0
}

func (m *Params) GetMaxSourceUrlBytes() uint32 {
	if m != nil {
		return m.MaxSourceUrlBytes
	}
	return 0
}

func (m *Params) GetMaxVersionBytes() uint32 {
	if m != nil {
		return m.MaxVersionBytes
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "glassharbor.registry.v1.Params")
}

func init() {
	proto.RegisterFile("glassharbor/registry/v1/params.proto", fileDescriptor_38670aa0275c922c)
}

var fileDescriptor_38670aa0275c922c = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x4f, 0xe3, 0x46,
	0x18, 0xc6, 0xe3, 0xd2, 0x02, 0x19, 0x12, 0x42, 0x4c, 0x10, 0x06, 0x24, 0x13, 0x21, 0x54, 0x45,
	0x48, 0xd8, 0x0a, 0xbd, 0x55, 0xbd, 0x10, 0x22, 0xd4, 0xd2, 0x56, 0x42, 0x81, 0xb6, 0x52, 0x2f,
	0xd6, 0xd8, 0x79, 0x71, 0x06, 0x6c, 0x8f, 0x35, 0x33, 0xce, 0x26, 0x5f, 0x61, 0x4f, 0x7b, 0xdc,
	0x8f, 0xb0, 0x47, 0x0e, 0x7c, 0x08, 0x8e, 0x88, 0xd3, 0x6a, 0x0f, 0xec, 0x0a, 0x0e, 0x7c, 0x85,
	0x3d, 0xae, 0xe6, 0x4f, 0x02, 0xec, 0x6d, 0xf7, 0x12, 0x65, 0xde, 0xf7, 0xf7, 0x3c, 0xcf, 0x9b,
	0xd1, 0x9b, 0x41, 0xdb, 0x71, 0x82, 0x39, 0x1f, 0x60, 0x16, 0x52, 0xe6, 0x33, 0x88, 0x09, 0x17,
	0x6c, 0xec, 0x0f, 0xdb, 0x7e, 0x8e, 0x19, 0x4e, 0xb9, 0x97, 0x33, 0x2a, 0xa8, 0xbd, 0xfa, 0x8c,
	0xf2, 0x26, 0x94, 0x37, 0x6c, 0xaf, 0xd7, 0x71, 0x4a, 0x32, 0xea, 0xab, 0x4f, 0xcd, 0xae, 0xbb,
	0x11, 0xe5, 0x29, 0xe5, 0x7e, 0x88, 0x39, 0xf8, 0xc3, 0x76, 0x08, 0x02, 0xb7, 0xfd, 0x88, 0x92,
	0xcc, 0xf4, 0xd7, 0x74, 0x3f, 0x50, 0x27, 0x5f, 0x1f, 0x4c, 0xab, 0x11, 0xd3, 0x98, 0xea, 0xba,
	0xfc, 0x36, 0x31, 0x8c, 0x29, 0x8d, 0x13, 0xf0, 0xd5, 0x29, 0x2c, 0xce, 0xfc, 0x7e, 0xc1, 0xb0,
	0x20, 0xd4, 0x18, 0x6e, 0x7d, 0x9e, 0x43, 0xb3, 0xc7, 0x6a, 0x5a, 0xfb, 0x08, 0x2d, 0x46, 0x0c,
	0xb0, 0x80, 0x00, 0xe7, 0x79, 0x70, 0x06, 0xe0, 0x58, 0x4d, 0xab, 0xb5, 0xb0, 0xb7, 0xe6, 0x99,
	0x1c, 0x39, 0x94, 0x67, 0x86, 0xf2, 0x0e, 0x28, 0xc9, 0x3a, 0xe5, 0xeb, 0xbb, 0xcd, 0xd2, 0xbb,
	0xc7, 0xcb, 0x1d, 0xab, 0x57, 0xd1, 0xda, 0xfd, 0x3c, 0x3f, 0x04, 0xb0, 0x4f, 0xd1, 0x72, 0x5e,
	0x84, 0x09, 0xe1, 0x83, 0x60, 0x08, 0x8c, 0x13, 0x9a, 0x29, 0xc3, 0x1f, 0xbe, 0xc1, 0xb0, 0x6e,
	0x0c, 0xfe, 0xd5, 0x7a, 0xe9, 0x7a, 0x8e, 0x9c, 0x22, 0x4f, 0x28, 0xee, 0x4b, 0xb3, 0x40, 0x30,
	0xc0, 0xbc, 0x60, 0xe3, 0x80, 0x61, 0x01, 0xce, 0x4c, 0xd3, 0x6a, 0x95, 0x3b, 0x6d, 0xa9, 0xff,
	0x70, 0xb7, 0xb9, 0xa1, 0x13, 0x78, 0xff, 0xc2, 0x23, 0xd4, 0x4f, 0xb1, 0x18, 0x78, 0x7f, 0x41,
	0x8c, 0xa3, 0x71, 0x17, 0xa2, 0xdb, 0xab, 0x5d, 0x64, 0x06, 0xe8, 0x42, 0xd4, 0x5b, 0xd1, 0x96,
	0x87, 0x00, 0xa7, 0xc6, 0xb0, 0x87, 0x05, 0xd8, 0x04, 0xad, 0x86, 0x49, 0x01, 0xd1, 0x00, 0xa2,
	0x8b, 0xaf, 0xa2, 0x7e, 0xfc, 0xee, 0xa8, 0xa9, 0xe3, 0x8b, 0xa8, 0x03, 0xb4, 0x34, 0x0d, 0xc0,
	0xfd, 0x3e, 0x03, 0xce, 0x9d, 0x9f, 0x54, 0x86, 0x73, 0x7b, 0xb5, 0xdb, 0x30, 0x06, 0xfb, 0xba,
	0x73, 0x22, 0x18, 0xc9, 0xe2, 0x5e, 0x6d, 0xa2, 0x30, 0x65, 0xfb, 0x77, 0x54, 0x1d, 0x52, 0x41,
	0xb2, 0x38, 0xc8, 0x81, 0x11, 0xda, 0x77, 0x66, 0xcd, 0x5d, 0xeb, 0x05, 0xf0, 0x26, 0x0b, 0xe0,
	0x75, 0xcd, 0x02, 0x74, 0xe6, 0xe5, 0x0f, 0x78, 0xfb, 0x71, 0xd3, 0xea, 0x55, 0xb4, 0xf2, 0x58,
	0x09, 0x6d, 0x17, 0xa1, 0x08, 0x0b, 0x88, 0x29, 0x23, 0xc0, 0x9d, 0xb9, 0xe6, 0x4c, 0xab, 0xdc,
	0x7b, 0x56, 0xb1, 0x7f, 0x46, 0xb5, 0x14, 0x8f, 0x02, 0x41, 0x44, 0x02, 0x41, 0x38, 0x16, 0xc0,
	0x9d, 0xf9, 0xa6, 0xd5, 0xaa, 0xf6, 0xaa, 0x29, 0x1e, 0x9d, 0xca, 0x6a, 0x47, 0x16, 0xed, 0x3d,
	0xb4, 0x22, 0xb9, 0x3e, 0xf0, 0x88, 0x91, 0x5c, 0x46, 0x1a, 0xba, 0xac, 0xe8, 0xe5, 0x14, 0x8f,
	0xba, 0x4f, 0x3d, 0xad, 0x59, 0x43, 0xf3, 0xca, 0x1b, 0xc7, 0xdc, 0x41, 0x0a, 0x9b, 0x93, 0xa6,
	0x38, 0xe6, 0xf6, 0x16, 0xaa, 0x9a, 0x96, 0xb1, 0x59, 0x50, 0xfd, 0x05, 0xdd, 0xd7, 0xf2, 0x6d,
	0xb4, 0x28, 0x19, 0x12, 0x4d, 0xb3, 0x2a, 0x0a, 0xaa, 0xa4, 0x78, 0xf4, 0x47, 0x34, 0x09, 0x69,
	0xa1, 0x25, 0x49, 0xa5, 0x38, 0xce, 0x40, 0x18, 0xae, 0xaa, 0x38, 0xa9, 0xfe, 0x5b, 0x95, 0x35,
	0xf9, 0x1b, 0xda, 0x50, 0x24, 0xc9, 0x82, 0x73, 0x10, 0x62, 0x3c, 0x5d, 0x66, 0x2d, 0x5a, 0x54,
	0xa2, 0x55, 0x29, 0x22, 0xd9, 0x91, 0x04, 0xcc, 0xb2, 0x6a, 0xf5, 0x0e, 0xaa, 0x4b, 0xf5, 0x2b,
	0x08, 0x39, 0x11, 0x93, 0xab, 0xaa, 0x29, 0x8d, 0xbc, 0xc1, 0xff, 0x74, 0x5d, 0xb3, 0x3e, 0x6a,
	0x48, 0x96, 0xd3, 0x82, 0x45, 0x10, 0x14, 0x2c, 0x31, 0xf8, 0x92, 0xc2, 0xa5, 0xcf, 0x89, 0x6a,
	0xfd, 0xc3, 0x92, 0x17, 0xe6, 0x2f, 0x07, 0xaa, 0x4f, 0xcd, 0x9f, 0x0f, 0xf2, 0x6b, 0xe3, 0xf5,
	0xe3, 0xe5, 0x4e, 0x6d, 0xfa, 0x40, 0xe9, 0xff, 0x7b, 0xe7, 0xcf, 0xeb, 0x7b, 0xd7, 0xba, 0xb9,
	0x77, 0xad, 0x4f, 0xf7, 0xae, 0xf5, 0xe6, 0xc1, 0x2d, 0xdd, 0x3c, 0xb8, 0xa5, 0xf7, 0x0f, 0x6e,
	0xe9, 0xff, 0x76, 0x4c, 0xc4, 0xa0, 0x08, 0xbd, 0x88, 0xa6, 0xbe, 0x7a, 0xbc, 0x76, 0xcd, 0x1b,
	0xa7, 0x96, 0x28, 0xa2, 0x89, 0x3f, 0x7a, 0x7a, 0xee, 0xc4, 0x38, 0x07, 0x1e, 0xce, 0xaa, 0xd6,
	0x2f, 0x5f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0xd1, 0xb2, 0xbb, 0x13, 0x05, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxVersionBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxVersionBytes))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.MaxSourceUrlBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSourceUrlBytes))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.MaxWebsiteBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxWebsiteBytes))
		i--
		dAtA[i] = 0x78
	}
	if m.MaxMinJettyVersionBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMinJettyVersionBytes))
		i--
		dAtA[i] = 0x70
	}
	if m.MaxMagnetBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMagnetBytes))
		i--
		dAtA[i] = 0x68
	}
	if m.MaxIconBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxIconBytes))
		i--
		dAtA[i] = 0x60
	}
	if m.MaxTagBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTagBytes))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxTags != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTags))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxDescriptionBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDescriptionBytes))
		i--
		dAtA[i] = 0x48
	}
	if m.MaxTitleBytes != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTitleBytes))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Categories) > 0 {
		for iNdEx := len(m.Categories) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Categories[iNdEx])
			copy(dAtA[i:], m.Categories[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Categories[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.VotingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VotingPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	if len(m.TreasuryAddress) > 0 {
		i -= len(m.TreasuryAddress)
		copy(dAtA[i:], m.TreasuryAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TreasuryAddress)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size := m.BluecheckTreasuryRate.Size()
		i -= size
		if _, err := m.BluecheckTreasuryRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.UploadFeeTreasuryRate.Size()
		i -= size
		if _, err := m.UploadFeeTreasuryRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.PublishVersionFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CreateAppFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CreateAppFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.PublishVersionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.UploadFeeTreasuryRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BluecheckTreasuryRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.TreasuryAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VotingPeriod)
	n += 1 + l + sovParams(uint64(l))
	if len(m.Categories) > 0 {
		for _, s := range m.Categories {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MaxTitleBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxTitleBytes))
	}
	if m.MaxDescriptionBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxDescriptionBytes))
	}
	if m.MaxTags != 0 {
		n += 1 + sovParams(uint64(m.MaxTags))
	}
	if m.MaxTagBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxTagBytes))
	}
	if m.MaxIconBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxIconBytes))
	}
	if m.MaxMagnetBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxMagnetBytes))
	}
	if m.MaxMinJettyVersionBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxMinJettyVersionBytes))
	}
	if m.MaxWebsiteBytes != 0 {
		n += 1 + sovParams(uint64(m.MaxWebsiteBytes))
	}
	if m.MaxSourceUrlBytes != 0 {
		n += 2 + sovParams(uint64(m.MaxSourceUrlBytes))
	}
	if m.MaxVersionBytes != 0 {
		n += 2 + sovParams(uint64(m.MaxVersionBytes))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateAppFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateAppFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishVersionFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PublishVersionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadFeeTreasuryRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UploadFeeTreasuryRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BluecheckTreasuryRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BluecheckTreasuryRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.VotingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Categories", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Categories = append(m.Categories, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTitleBytes", wireType)
			}
			m.MaxTitleBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTitleBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDescriptionBytes", wireType)
			}
			m.MaxDescriptionBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDescriptionBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTags", wireType)
			}
			m.MaxTags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTags |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTagBytes", wireType)
			}
			m.MaxTagBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTagBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxIconBytes", wireType)
			}
			m.MaxIconBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxIconBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMagnetBytes", wireType)
			}
			m.MaxMagnetBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMagnetBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMinJettyVersionBytes", wireType)
			}
			m.MaxMinJettyVersionBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMinJettyVersionBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWebsiteBytes", wireType)
			}
			m.MaxWebsiteBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWebsiteBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSourceUrlBytes", wireType)
			}
			m.MaxSourceUrlBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSourceUrlBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVersionBytes", wireType)
			}
			m.MaxVersionBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVersionBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
