// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: glassharbor/registry/v1/registry.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RequestKind distinguishes verification from revocation requests.
type RequestKind int32

const (
	REQUEST_KIND_UNSPECIFIED RequestKind = 0
	REQUEST_KIND_VERIFY      RequestKind = 1
	REQUEST_KIND_REVOKE      RequestKind = 2
)

var RequestKind_name = map[int32]string{
	0: "REQUEST_KIND_UNSPECIFIED",
	1: "REQUEST_KIND_VERIFY",
	2: "REQUEST_KIND_REVOKE",
}

var RequestKind_value = map[string]int32{
	"REQUEST_KIND_UNSPECIFIED": 0,
	"REQUEST_KIND_VERIFY":      1,
	"REQUEST_KIND_REVOKE":      2,
}

func (x RequestKind) String() string {
	return proto.EnumName(RequestKind_name, int32(x))
}

func (RequestKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{0}
}

// RequestStatus is the lifecycle state of a request.
type RequestStatus int32

const (
	REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	REQUEST_STATUS_OPEN        RequestStatus = 1
	REQUEST_STATUS_PASSED      RequestStatus = 2
	REQUEST_STATUS_FAILED      RequestStatus = 3
	REQUEST_STATUS_CANCELLED   RequestStatus = 4
)

var RequestStatus_name = map[int32]string{
	0: "REQUEST_STATUS_UNSPECIFIED",
	1: "REQUEST_STATUS_OPEN",
	2: "REQUEST_STATUS_PASSED",
	3: "REQUEST_STATUS_FAILED",
	4: "REQUEST_STATUS_CANCELLED",
}

var RequestStatus_value = map[string]int32{
	"REQUEST_STATUS_UNSPECIFIED": 0,
	"REQUEST_STATUS_OPEN":        1,
	"REQUEST_STATUS_PASSED":      2,
	"REQUEST_STATUS_FAILED":      3,
	"REQUEST_STATUS_CANCELLED":   4,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{1}
}

// VoteOption is a validator's vote on a request.
type VoteOption int32

const (
	VOTE_OPTION_UNSPECIFIED VoteOption = 0
	VOTE_OPTION_YES         VoteOption = 1
	VOTE_OPTION_NO          VoteOption = 2
)

var VoteOption_name = map[int32]string{
	0: "VOTE_OPTION_UNSPECIFIED",
	1: "VOTE_OPTION_YES",
	2: "VOTE_OPTION_NO",
}

var VoteOption_value = map[string]int32{
	"VOTE_OPTION_UNSPECIFIED": 0,
	"VOTE_OPTION_YES":         1,
	"VOTE_OPTION_NO":          2,
}

func (x VoteOption) String() string {
	return proto.EnumName(VoteOption_name, int32(x))
}

func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{2}
}

// App is a registered application (SPEC §6.2).
type App struct {
	Id          uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner       string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Title       string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon        []byte   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	IconMime    string   `protobuf:"bytes,6,opt,name=icon_mime,json=iconMime,proto3" json:"icon_mime,omitempty"`
	Website     string   `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	SourceUrl   string   `protobuf:"bytes,8,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Category    string   `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	Tags        []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Deprecated  bool     `protobuf:"varint,11,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// latest_version is the semver of the version with the highest seq; empty if none.
	LatestVersion string `protobuf:"bytes,12,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	// version_count is the number of versions ever published; also the next seq.
	VersionCount  uint64 `protobuf:"varint,13,opt,name=version_count,json=versionCount,proto3" json:"version_count,omitempty"`
	CreatedHeight int64  `protobuf:"varint,14,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	UpdatedHeight int64  `protobuf:"varint,15,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{0}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_App.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return m.Size()
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *App) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *App) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *App) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *App) GetIcon() []byte {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *App) GetIconMime() string {
	if m != nil {
		return m.IconMime
	}
	return ""
}

func (m *App) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *App) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *App) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *App) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *App) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

func (m *App) GetLatestVersion() string {
	if m != nil {
		return m.LatestVersion
	}
	return ""
}

func (m *App) GetVersionCount() uint64 {
	if m != nil {
		return m.VersionCount
	}
	return 0
}

func (m *App) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *App) GetUpdatedHeight() int64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

// Version is an immutable release of an app (SPEC §6.2).
type Version struct {
	AppId              uint64    `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Version            string    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Seq                uint64    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Magnet             string    `protobuf:"bytes,4,opt,name=magnet,proto3" json:"magnet,omitempty"`
	ChecksumSha256     string    `protobuf:"bytes,5,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	FileSize           uint64    `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MinJettyVersion    string    `protobuf:"bytes,7,opt,name=min_jetty_version,json=minJettyVersion,proto3" json:"min_jetty_version,omitempty"`
	Publisher          string    `protobuf:"bytes,8,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublishHeight      int64     `protobuf:"varint,9,opt,name=publish_height,json=publishHeight,proto3" json:"publish_height,omitempty"`
	PublishTime        time.Time `protobuf:"bytes,10,opt,name=publish_time,json=publishTime,proto3,stdtime" json:"publish_time"`
	Yanked             bool      `protobuf:"varint,11,opt,name=yanked,proto3" json:"yanked,omitempty"`
	BlueCheck          bool      `protobuf:"varint,12,opt,name=blue_check,json=blueCheck,proto3" json:"blue_check,omitempty"`
	BlueCheckRequestId uint64    `protobuf:"varint,13,opt,name=blue_check_request_id,json=blueCheckRequestId,proto3" json:"blue_check_request_id,omitempty"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{1}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Version.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return m.Size()
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Version) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Version) GetMagnet() string {
	if m != nil {
		return m.Magnet
	}
	return ""
}

func (m *Version) GetChecksumSha256() string {
	if m != nil {
		return m.ChecksumSha256
	}
	return ""
}

func (m *Version) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Version) GetMinJettyVersion() string {
	if m != nil {
		return m.MinJettyVersion
	}
	return ""
}

func (m *Version) GetPublisher() string {
	if m != nil {
		return m.Publisher
	}
	return ""
}

func (m *Version) GetPublishHeight() int64 {
	if m != nil {
		return m.PublishHeight
	}
	return 0
}

func (m *Version) GetPublishTime() time.Time {
	if m != nil {
		return m.PublishTime
	}
	return time.Time{}
}

func (m *Version) GetYanked() bool {
	if m != nil {
		return m.Yanked
	}
	return false
}

func (m *Version) GetBlueCheck() bool {
	if m != nil {
		return m.BlueCheck
	}
	return false
}

func (m *Version) GetBlueCheckRequestId() uint64 {
	if m != nil {
		return m.BlueCheckRequestId
	}
	return 0
}

// Request is a blue-check verification or revocation request (SPEC §6.2).
type Request struct {
	Id             uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind           RequestKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=glassharbor.registry.v1.RequestKind" json:"kind,omitempty"`
	AppId          uint64                `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Version        string                `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Requester      string                `protobuf:"bytes,5,opt,name=requester,proto3" json:"requester,omitempty"`
	Escrow         types.Coin            `protobuf:"bytes,6,opt,name=escrow,proto3" json:"escrow"`
	Status         RequestStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=glassharbor.registry.v1.RequestStatus" json:"status,omitempty"`
	SubmitHeight   int64                 `protobuf:"varint,8,opt,name=submit_height,json=submitHeight,proto3" json:"submit_height,omitempty"`
	SubmitTime     time.Time             `protobuf:"bytes,9,opt,name=submit_time,json=submitTime,proto3,stdtime" json:"submit_time"`
	ExpiresAt      time.Time             `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at"`
	ResolvedHeight int64                 `protobuf:"varint,11,opt,name=resolved_height,json=resolvedHeight,proto3" json:"resolved_height,omitempty"`
	YesPower       cosmossdk_io_math.Int `protobuf:"bytes,12,opt,name=yes_power,json=yesPower,proto3,customtype=cosmossdk.io/math.Int" json:"yes_power"`
	NoPower        cosmossdk_io_math.Int `protobuf:"bytes,13,opt,name=no_power,json=noPower,proto3,customtype=cosmossdk.io/math.Int" json:"no_power"`
	TotalPower     cosmossdk_io_math.Int `protobuf:"bytes,14,opt,name=total_power,json=totalPower,proto3,customtype=cosmossdk.io/math.Int" json:"total_power"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return m.Size()
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetKind() RequestKind {
	if m != nil {
		return m.Kind
	}
	return REQUEST_KIND_UNSPECIFIED
}

func (m *Request) GetAppId() uint64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *Request) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Request) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *Request) GetEscrow() types.Coin {
	if m != nil {
		return m.Escrow
	}
	return types.Coin{}
}

func (m *Request) GetStatus() RequestStatus {
	if m != nil {
		return m.Status
	}
	return REQUEST_STATUS_UNSPECIFIED
}

func (m *Request) GetSubmitHeight() int64 {
	if m != nil {
		return m.SubmitHeight
	}
	return 0
}

func (m *Request) GetSubmitTime() time.Time {
	if m != nil {
		return m.SubmitTime
	}
	return time.Time{}
}

func (m *Request) GetExpiresAt() time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return time.Time{}
}

func (m *Request) GetResolvedHeight() int64 {
	if m != nil {
		return m.ResolvedHeight
	}
	return 0
}

// Vote is a validator's current vote on a request.
type Vote struct {
	RequestId uint64     `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Validator string     `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Option    VoteOption `protobuf:"varint,3,opt,name=option,proto3,enum=glassharbor.registry.v1.VoteOption" json:"option,omitempty"`
	Height    int64      `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e497a22bb09e29a4, []int{3}
}
func (m *Vote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return m.Size()
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Vote) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *Vote) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VOTE_OPTION_UNSPECIFIED
}

func (m *Vote) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("glassharbor.registry.v1.RequestKind", RequestKind_name, RequestKind_value)
	proto.RegisterEnum("glassharbor.registry.v1.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterEnum("glassharbor.registry.v1.VoteOption", VoteOption_name, VoteOption_value)
	proto.RegisterType((*App)(nil), "glassharbor.registry.v1.App")
	proto.RegisterType((*Version)(nil), "glassharbor.registry.v1.Version")
	proto.RegisterType((*Request)(nil), "glassharbor.registry.v1.Request")
	proto.RegisterType((*Vote)(nil), "glassharbor.registry.v1.Vote")
}

func init() {
	proto.RegisterFile("glassharbor/registry/v1/registry.proto", fileDescriptor_e497a22bb09e29a4)
}

var fileDescriptor_e497a22bb09e29a4 = []byte{
	// 1233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x8f, 0x62, 0xc7, 0xb1, 0x9e, 0x13, 0xc7, 0xdd, 0x36, 0x54, 0x4d, 0xa9, 0x63, 0x52, 0x28,
	0x9e, 0x30, 0x91, 0x27, 0x61, 0xe8, 0x30, 0x03, 0x03, 0xe3, 0x38, 0x0a, 0x35, 0x29, 0x71, 0x90,
	0x93, 0x0c, 0xe5, 0xa2, 0x91, 0xad, 0xad, 0xbd, 0xc4, 0xd2, 0xaa, 0xda, 0x75, 0x52, 0xf7, 0x13,
	0x70, 0xec, 0x67, 0x80, 0x0b, 0x47, 0x0e, 0xbd, 0xf1, 0x05, 0x7a, 0x2c, 0x3d, 0x31, 0x1c, 0x0a,
	0xd3, 0x1e, 0xe0, 0x03, 0xf0, 0x01, 0x98, 0xfd, 0x23, 0xc7, 0x6d, 0x49, 0x99, 0x5c, 0xec, 0x7d,
	0xbf, 0xdf, 0x7b, 0x4f, 0xbb, 0xef, 0xfd, 0xde, 0x4a, 0x70, 0xa3, 0x37, 0xf0, 0x19, 0xeb, 0xfb,
	0x49, 0x87, 0x26, 0xb5, 0x04, 0xf7, 0x08, 0xe3, 0xc9, 0xa8, 0x76, 0xbc, 0x3e, 0x5e, 0xdb, 0x71,
	0x42, 0x39, 0x45, 0x97, 0x27, 0xfc, 0xec, 0x31, 0x77, 0xbc, 0xbe, 0x74, 0xc1, 0x0f, 0x49, 0x44,
	0x6b, 0xf2, 0x57, 0xf9, 0x2e, 0x95, 0xbb, 0x94, 0x85, 0x94, 0xd5, 0x3a, 0x3e, 0xc3, 0xb5, 0xe3,
	0xf5, 0x0e, 0xe6, 0xfe, 0x7a, 0xad, 0x4b, 0x49, 0xa4, 0xf9, 0x2b, 0x8a, 0xf7, 0xa4, 0x55, 0x53,
	0x86, 0xa6, 0x2e, 0xf5, 0x68, 0x8f, 0x2a, 0x5c, 0xac, 0x34, 0xba, 0xdc, 0xa3, 0xb4, 0x37, 0xc0,
	0x35, 0x69, 0x75, 0x86, 0x77, 0x6b, 0x9c, 0x84, 0x98, 0x71, 0x3f, 0x8c, 0x95, 0xc3, 0xca, 0xaf,
	0x19, 0xc8, 0xd4, 0xe3, 0x18, 0x15, 0x61, 0x9a, 0x04, 0x96, 0x51, 0x31, 0xaa, 0x59, 0x77, 0x9a,
	0x04, 0xc8, 0x86, 0x19, 0x7a, 0x12, 0xe1, 0xc4, 0x9a, 0xae, 0x18, 0x55, 0x73, 0xd3, 0x7a, 0xfa,
	0x68, 0xed, 0x92, 0x7e, 0x5e, 0x3d, 0x08, 0x12, 0xcc, 0x58, 0x9b, 0x27, 0x24, 0xea, 0xb9, 0xca,
	0x0d, 0x5d, 0x82, 0x19, 0x4e, 0xf8, 0x00, 0x5b, 0x19, 0xe1, 0xef, 0x2a, 0x03, 0x55, 0xa0, 0x10,
	0x60, 0xd6, 0x4d, 0x48, 0xcc, 0x09, 0x8d, 0xac, 0xac, 0xe4, 0x26, 0x21, 0x84, 0x20, 0x4b, 0xba,
	0x34, 0xb2, 0x66, 0x2a, 0x46, 0x75, 0xce, 0x95, 0x6b, 0x74, 0x15, 0x4c, 0xf1, 0xef, 0x85, 0x24,
	0xc4, 0x56, 0x4e, 0xc6, 0xe4, 0x05, 0xf0, 0x15, 0x09, 0x31, 0xb2, 0x60, 0xf6, 0x04, 0x77, 0x18,
	0xe1, 0xd8, 0x9a, 0x95, 0x54, 0x6a, 0xa2, 0x6b, 0x00, 0x8c, 0x0e, 0x93, 0x2e, 0xf6, 0x86, 0xc9,
	0xc0, 0xca, 0x4b, 0xd2, 0x54, 0xc8, 0x41, 0x32, 0x40, 0x4b, 0x90, 0xef, 0xfa, 0x1c, 0xf7, 0x68,
	0x32, 0xb2, 0x4c, 0x95, 0x34, 0xb5, 0xc5, 0x2e, 0xb8, 0xdf, 0x63, 0x16, 0x54, 0x32, 0x55, 0xd3,
	0x95, 0x6b, 0x54, 0x06, 0x08, 0x70, 0x9c, 0x60, 0xe1, 0x14, 0x58, 0x85, 0x8a, 0x51, 0xcd, 0xbb,
	0x13, 0x08, 0x7a, 0x0f, 0x8a, 0x03, 0x9f, 0x63, 0xc6, 0xbd, 0x63, 0x9c, 0x30, 0x71, 0xbc, 0x39,
	0x99, 0x75, 0x5e, 0xa1, 0x87, 0x0a, 0x44, 0xd7, 0x61, 0x5e, 0xf3, 0x5e, 0x97, 0x0e, 0x23, 0x6e,
	0xcd, 0xcb, 0x1a, 0xcf, 0x69, 0xb0, 0x21, 0x30, 0x91, 0xab, 0x9b, 0x60, 0x91, 0xd6, 0xeb, 0x63,
	0xd2, 0xeb, 0x73, 0xab, 0x58, 0x31, 0xaa, 0x19, 0x77, 0x5e, 0xa3, 0xb7, 0x24, 0x28, 0xdc, 0x86,
	0x71, 0x30, 0xe9, 0xb6, 0xa0, 0xdc, 0x34, 0xaa, 0xdc, 0x56, 0xfe, 0xce, 0xc0, 0x6c, 0xfa, 0xf8,
	0x45, 0xc8, 0xf9, 0x71, 0xec, 0x8d, 0x7b, 0x3b, 0xe3, 0xc7, 0x71, 0x33, 0x10, 0x55, 0x4c, 0x77,
	0x3d, 0xad, 0xaa, 0xa8, 0x4d, 0x54, 0x82, 0x0c, 0xc3, 0xf7, 0x64, 0x1b, 0xb3, 0xae, 0x58, 0xa2,
	0xb7, 0x20, 0x17, 0xfa, 0xbd, 0x08, 0x73, 0xdd, 0x3f, 0x6d, 0xa1, 0xf7, 0x61, 0xa1, 0xdb, 0xc7,
	0xdd, 0x23, 0x36, 0x0c, 0x3d, 0xd6, 0xf7, 0x37, 0x3e, 0xba, 0x29, 0xbb, 0x68, 0xba, 0xc5, 0x14,
	0x6e, 0x4b, 0x54, 0xf4, 0xf3, 0x2e, 0x19, 0x60, 0x8f, 0x91, 0x07, 0xaa, 0x9f, 0x59, 0x37, 0x2f,
	0x80, 0x36, 0x79, 0x80, 0xd1, 0x2a, 0x5c, 0x08, 0x49, 0xe4, 0x7d, 0x87, 0x39, 0x1f, 0x8d, 0x2b,
	0xa9, 0x3a, 0xbb, 0x10, 0x92, 0xe8, 0x4b, 0x81, 0xa7, 0x87, 0xb9, 0x09, 0x66, 0x3c, 0xec, 0x0c,
	0x08, 0xeb, 0xe3, 0x44, 0x35, 0xf8, 0x0d, 0xc2, 0x3c, 0x75, 0x15, 0x75, 0xd3, 0x46, 0x5a, 0x37,
	0x53, 0xd5, 0x4d, 0xa3, 0xba, 0xbc, 0x5f, 0xc0, 0x5c, 0xea, 0x26, 0xc6, 0xc4, 0x82, 0x8a, 0x51,
	0x2d, 0x6c, 0x2c, 0xd9, 0x6a, 0x86, 0xec, 0x74, 0x86, 0xec, 0xfd, 0x74, 0x86, 0x36, 0xf3, 0x8f,
	0x9f, 0x2d, 0x4f, 0x3d, 0xfc, 0x63, 0xd9, 0x70, 0x0b, 0x3a, 0x52, 0x70, 0xa2, 0x62, 0x23, 0x3f,
	0x3a, 0x1a, 0xcb, 0x46, 0x5b, 0x42, 0xa1, 0x9d, 0xc1, 0x10, 0x7b, 0xb2, 0x3e, 0x52, 0x2e, 0x79,
	0xd7, 0x14, 0x48, 0x43, 0x00, 0x68, 0x1d, 0x16, 0x4f, 0x69, 0x2f, 0xc1, 0xf7, 0x86, 0x42, 0x5d,
	0x24, 0xd0, 0x92, 0x41, 0x63, 0x4f, 0x57, 0x51, 0xcd, 0x60, 0xe5, 0x9f, 0x19, 0x98, 0xd5, 0xd6,
	0x6b, 0x23, 0xfc, 0x31, 0x64, 0x8f, 0x48, 0x14, 0xc8, 0x06, 0x17, 0x37, 0xde, 0xb5, 0xcf, 0xb8,
	0x87, 0x6c, 0x1d, 0xbf, 0x43, 0xa2, 0xc0, 0x95, 0x11, 0x13, 0xa2, 0xc9, 0x9c, 0x21, 0x9a, 0xec,
	0xcb, 0xa2, 0xb9, 0x09, 0xa6, 0xde, 0x2e, 0x4e, 0x94, 0x08, 0xde, 0xd4, 0x98, 0xb1, 0x2b, 0xfa,
	0x14, 0x72, 0xe2, 0x2e, 0xa0, 0x27, 0x52, 0x16, 0x85, 0x8d, 0x2b, 0xb6, 0x8e, 0x10, 0x17, 0xa0,
	0xad, 0x2f, 0x40, 0xbb, 0x41, 0x49, 0xb4, 0x69, 0x8a, 0x52, 0xff, 0xf4, 0xd7, 0xcf, 0xab, 0x86,
	0xab, 0x63, 0xd0, 0x67, 0x90, 0x63, 0xdc, 0xe7, 0x43, 0x26, 0xf5, 0x52, 0xdc, 0xb8, 0xf1, 0x7f,
	0x47, 0x6c, 0x4b, 0x6f, 0x57, 0x47, 0x89, 0xd1, 0x64, 0xc3, 0x4e, 0x48, 0x78, 0xaa, 0x8a, 0xbc,
	0x54, 0xc5, 0x9c, 0x02, 0xb5, 0x28, 0x1c, 0x28, 0x68, 0x27, 0xa9, 0x09, 0xf3, 0x1c, 0x9a, 0x00,
	0x15, 0x28, 0x25, 0xd1, 0x00, 0xc0, 0xf7, 0x63, 0x92, 0x60, 0xe6, 0xf9, 0xfc, 0x5c, 0xca, 0x32,
	0x75, 0x5c, 0x5d, 0x4e, 0x5c, 0x82, 0x19, 0x1d, 0x1c, 0x9f, 0x5e, 0x00, 0x05, 0xb9, 0xe5, 0x62,
	0x0a, 0xeb, 0x4d, 0xdf, 0x02, 0x73, 0x84, 0x99, 0x17, 0xd3, 0x13, 0x9c, 0xa8, 0x6b, 0x69, 0xf3,
	0x03, 0x91, 0xf0, 0xf7, 0x67, 0xcb, 0x8b, 0xaa, 0xc2, 0x2c, 0x38, 0xb2, 0x09, 0xad, 0x85, 0x3e,
	0xef, 0xdb, 0xcd, 0x88, 0x3f, 0x7d, 0xb4, 0x06, 0xba, 0xf4, 0xcd, 0x88, 0xbb, 0xf9, 0x11, 0x66,
	0x7b, 0x22, 0x18, 0x6d, 0x43, 0x3e, 0xa2, 0x3a, 0xd1, 0xfc, 0xf9, 0x13, 0xcd, 0x46, 0x54, 0xe5,
	0xb9, 0x0d, 0x05, 0x4e, 0xb9, 0x3f, 0xd0, 0xa9, 0x8a, 0xe7, 0x4f, 0x05, 0x32, 0x5e, 0x66, 0x5b,
	0xf9, 0xc5, 0x80, 0xec, 0x21, 0x55, 0x77, 0xfe, 0xc4, 0x9c, 0x28, 0xed, 0xa7, 0xfa, 0x6a, 0x06,
	0xe8, 0x73, 0x30, 0x8f, 0xfd, 0x01, 0x09, 0x7c, 0x4e, 0xd3, 0x37, 0xd9, 0x3b, 0x4f, 0x1f, 0xad,
	0x5d, 0xd3, 0x69, 0x0f, 0x53, 0xee, 0x15, 0x81, 0x8e, 0x63, 0xd0, 0x27, 0x90, 0xa3, 0xea, 0xdd,
	0x95, 0x91, 0x12, 0xbb, 0x7e, 0xa6, 0xc4, 0xc4, 0x76, 0x5a, 0xd2, 0xd5, 0xd5, 0x21, 0xe2, 0x1a,
	0xd0, 0x5d, 0xca, 0xca, 0x2e, 0x69, 0x6b, 0xb5, 0x0b, 0x85, 0x89, 0x99, 0x43, 0x6f, 0x83, 0xe5,
	0x3a, 0x5f, 0x1f, 0x38, 0xed, 0x7d, 0x6f, 0xa7, 0xb9, 0xbb, 0xe5, 0x1d, 0xec, 0xb6, 0xf7, 0x9c,
	0x46, 0x73, 0xbb, 0xe9, 0x6c, 0x95, 0xa6, 0xd0, 0x65, 0xb8, 0xf8, 0x12, 0x7b, 0xe8, 0xb8, 0xcd,
	0xed, 0x3b, 0x25, 0xe3, 0x35, 0xc2, 0x75, 0x0e, 0x5b, 0x3b, 0x4e, 0x69, 0x7a, 0x29, 0xfb, 0xfd,
	0x8f, 0xe5, 0xa9, 0xd5, 0x1f, 0x0c, 0x98, 0x7f, 0x49, 0xf6, 0xa8, 0x0c, 0x4b, 0x69, 0x40, 0x7b,
	0xbf, 0xbe, 0x7f, 0xd0, 0x3e, 0xfb, 0x49, 0x9a, 0x6f, 0xed, 0x39, 0xbb, 0x25, 0x03, 0x5d, 0x81,
	0xc5, 0x57, 0x88, 0xbd, 0x7a, 0xbb, 0xed, 0x6c, 0x95, 0xa6, 0xff, 0x83, 0xda, 0xae, 0x37, 0x6f,
	0x3b, 0x5b, 0xa5, 0xcc, 0xe4, 0xb1, 0x34, 0xd5, 0xa8, 0xef, 0x36, 0x9c, 0xdb, 0x82, 0xcd, 0xea,
	0x4d, 0x7e, 0x03, 0x70, 0x5a, 0x37, 0x74, 0x15, 0x2e, 0x1f, 0xb6, 0xf6, 0x1d, 0xaf, 0xb5, 0xb7,
	0xdf, 0x6c, 0xed, 0xbe, 0xb2, 0xbb, 0x8b, 0xb0, 0x30, 0x49, 0xde, 0x71, 0xda, 0x25, 0x03, 0x21,
	0x28, 0x4e, 0x82, 0xbb, 0xad, 0xf4, 0xf8, 0x9b, 0x3b, 0x8f, 0x9f, 0x97, 0x8d, 0x27, 0xcf, 0xcb,
	0xc6, 0x9f, 0xcf, 0xcb, 0xc6, 0xc3, 0x17, 0xe5, 0xa9, 0x27, 0x2f, 0xca, 0x53, 0xbf, 0xbd, 0x28,
	0x4f, 0x7d, 0xbb, 0xde, 0x23, 0xbc, 0x3f, 0xec, 0xd8, 0x5d, 0x1a, 0xd6, 0x64, 0x33, 0xd7, 0xf4,
	0x37, 0x9c, 0x9c, 0xc2, 0x2e, 0x1d, 0xd4, 0xee, 0x9f, 0x7e, 0xce, 0xf1, 0x51, 0x8c, 0x59, 0x27,
	0x27, 0xa9, 0x0f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xac, 0xbf, 0xb9, 0xf3, 0x09, 0x00,
	0x00,
}

func (m *App) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *App) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *App) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedHeight != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x78
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x70
	}
	if m.VersionCount != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.VersionCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.LatestVersion) > 0 {
		i -= len(m.LatestVersion)
		copy(dAtA[i:], m.LatestVersion)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.LatestVersion)))
		i--
		dAtA[i] = 0x62
	}
	if m.Deprecated {
		i--
		if m.Deprecated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tags[iNdEx])
			copy(dAtA[i:], m.Tags[iNdEx])
			i = encodeVarintRegistry(dAtA, i, uint64(len(m.Tags[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SourceUrl) > 0 {
		i -= len(m.SourceUrl)
		copy(dAtA[i:], m.SourceUrl)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.SourceUrl)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.IconMime) > 0 {
		i -= len(m.IconMime)
		copy(dAtA[i:], m.IconMime)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.IconMime)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Icon) > 0 {
		i -= len(m.Icon)
		copy(dAtA[i:], m.Icon)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Icon)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Version) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Version) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Version) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlueCheckRequestId != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.BlueCheckRequestId))
		i--
		dAtA[i] = 0x68
	}
	if m.BlueCheck {
		i--
		if m.BlueCheck {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.Yanked {
		i--
		if m.Yanked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.PublishTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PublishTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintRegistry(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	if m.PublishHeight != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.PublishHeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Publisher) > 0 {
		i -= len(m.Publisher)
		copy(dAtA[i:], m.Publisher)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Publisher)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MinJettyVersion) > 0 {
		i -= len(m.MinJettyVersion)
		copy(dAtA[i:], m.MinJettyVersion)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.MinJettyVersion)))
		i--
		dAtA[i] = 0x3a
	}
	if m.FileSize != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.FileSize))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ChecksumSha256) > 0 {
		i -= len(m.ChecksumSha256)
		copy(dAtA[i:], m.ChecksumSha256)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.ChecksumSha256)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Magnet) > 0 {
		i -= len(m.Magnet)
		copy(dAtA[i:], m.Magnet)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Magnet)))
		i--
		dAtA[i] = 0x22
	}
	if m.Seq != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x12
	}
	if m.AppId != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalPower.Size()
		i -= size
		if _, err := m.TotalPower.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegistry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size := m.NoPower.Size()
		i -= size
		if _, err := m.NoPower.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegistry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size := m.YesPower.Size()
		i -= size
		if _, err := m.YesPower.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRegistry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.ResolvedHeight != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.ResolvedHeight))
		i--
		dAtA[i] = 0x58
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintRegistry(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x52
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.SubmitTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmitTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintRegistry(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x4a
	if m.SubmitHeight != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.SubmitHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Status != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.Escrow.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRegistry(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x22
	}
	if m.AppId != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x18
	}
	if m.Kind != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Vote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if m.Option != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.Option))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintRegistry(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.RequestId != 0 {
		i = encodeVarintRegistry(dAtA, i, uint64(m.RequestId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRegistry(dAtA []byte, offset int, v uint64) int {
	offset -= sovRegistry(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *App) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRegistry(uint64(m.Id))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Icon)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.IconMime)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.SourceUrl)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, s := range m.Tags {
			l = len(s)
			n += 1 + l + sovRegistry(uint64(l))
		}
	}
	if m.Deprecated {
		n += 2
	}
	l = len(m.LatestVersion)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if m.VersionCount != 0 {
		n += 1 + sovRegistry(uint64(m.VersionCount))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovRegistry(uint64(m.CreatedHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovRegistry(uint64(m.UpdatedHeight))
	}
	return n
}

func (m *Version) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AppId != 0 {
		n += 1 + sovRegistry(uint64(m.AppId))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if m.Seq != 0 {
		n += 1 + sovRegistry(uint64(m.Seq))
	}
	l = len(m.Magnet)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.ChecksumSha256)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if m.FileSize != 0 {
		n += 1 + sovRegistry(uint64(m.FileSize))
	}
	l = len(m.MinJettyVersion)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Publisher)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if m.PublishHeight != 0 {
		n += 1 + sovRegistry(uint64(m.PublishHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.PublishTime)
	n += 1 + l + sovRegistry(uint64(l))
	if m.Yanked {
		n += 2
	}
	if m.BlueCheck {
		n += 2
	}
	if m.BlueCheckRequestId != 0 {
		n += 1 + sovRegistry(uint64(m.BlueCheckRequestId))
	}
	return n
}

func (m *Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRegistry(uint64(m.Id))
	}
	if m.Kind != 0 {
		n += 1 + sovRegistry(uint64(m.Kind))
	}
	if m.AppId != 0 {
		n += 1 + sovRegistry(uint64(m.AppId))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	l = m.Escrow.Size()
	n += 1 + l + sovRegistry(uint64(l))
	if m.Status != 0 {
		n += 1 + sovRegistry(uint64(m.Status))
	}
	if m.SubmitHeight != 0 {
		n += 1 + sovRegistry(uint64(m.SubmitHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmitTime)
	n += 1 + l + sovRegistry(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpiresAt)
	n += 1 + l + sovRegistry(uint64(l))
	if m.ResolvedHeight != 0 {
		n += 1 + sovRegistry(uint64(m.ResolvedHeight))
	}
	l = m.YesPower.Size()
	n += 1 + l + sovRegistry(uint64(l))
	l = m.NoPower.Size()
	n += 1 + l + sovRegistry(uint64(l))
	l = m.TotalPower.Size()
	n += 1 + l + sovRegistry(uint64(l))
	return n
}

func (m *Vote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestId != 0 {
		n += 1 + sovRegistry(uint64(m.RequestId))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovRegistry(uint64(l))
	}
	if m.Option != 0 {
		n += 1 + sovRegistry(uint64(m.Option))
	}
	if m.Height != 0 {
		n += 1 + sovRegistry(uint64(m.Height))
	}
	return n
}

func sovRegistry(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRegistry(x uint64) (n int) {
	return sovRegistry(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *App) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: App: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: App: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Icon", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Icon = append(m.Icon[:0], dAtA[iNdEx:postIndex]...)
			if m.Icon == nil {
				m.Icon = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IconMime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IconMime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deprecated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Deprecated = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LatestVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VersionCount", wireType)
			}
			m.VersionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VersionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Version) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Version: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Version: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Magnet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Magnet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChecksumSha256", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChecksumSha256 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinJettyVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinJettyVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Publisher", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Publisher = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishHeight", wireType)
			}
			m.PublishHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublishHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublishTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.PublishTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yanked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Yanked = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlueCheck", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BlueCheck = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlueCheckRequestId", wireType)
			}
			m.BlueCheckRequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlueCheckRequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= RequestKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Escrow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Escrow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RequestStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitHeight", wireType)
			}
			m.SubmitHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmitHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.SubmitTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedHeight", wireType)
			}
			m.ResolvedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field YesPower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.YesPower.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoPower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NoPower.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalPower.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistry
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestId", wireType)
			}
			m.RequestId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistry
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistry
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			m.Option = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Option |= VoteOption(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRegistry(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistry
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegistry(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegistry
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistry
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRegistry
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRegistry
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRegistry
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRegistry        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegistry          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRegistry = fmt.Errorf("proto: unexpected end of group")
)
